### ISSUE TITLE
Cannot (always) interact with remote posts

### ISSUE THREAD

**Issue by Ekain06** [LemmurOrg/lemmur#307]
### Device info

- OS: Android (LineageOS + microg)
- OS version: 11
- Device: Pocophone F1
- Lemmur version: 0.7.0

### Describe the bug

I (seemingly randomly) cannot interact with posts from other instances in my feed -- the app tells me I am not logged in (even though I am and can interact with my instance's (lemmy.ml) and sometimes other's posts).

### Steps to reproduce

1. Open lemmurr.
2. Sort by everything - all.
3. Scroll until you find a post in another instance.
4. Try to vote (or comment) on it (sometimes it works, sometimes it doesn't)
5. Get told "you have to be logged in to do that [log in]" in the bottom of your screen.

### Relevant logs

<details>
  <summary>Logs</summary>
  
  Paste your logs here. Logs can be found in lemmur: settings > about lemmur > logs.

"no logs"
</details>

### Expected behavior

To be able to interact with posts in other instances consistently.

### Screenshots/Screencasts

![Screenshot_20211206-095358_lemmur](https://user-images.githubusercontent.com/76905934/144816673-000e7ec8-ca7e-4fbf-a938-6cdabe874520.png)
(Pressed the down arrow. I am logged in with a lemmy.ml account)

![Screenshot_20211206-095638_lemmur](https://user-images.githubusercontent.com/76905934/144816782-0fb29958-9b2d-4bff-98b7-da6bcebf3f18.png)

![Screenshot_20211206-095642_lemmur](https://user-images.githubusercontent.com/76905934/144816801-be82dc52-2dde-4cf2-8cbf-33bd45a84a9b.png)

### Additional context

- I'm using the FDroid build of the app.
- It seems like this is all client-side, since the app immediately shows me the error without the usual waiting when voting. There probably are some malformed checks in place.
- This may be related with #153

**Comment by krawieck** [comment]
this is because the context of the post is an instance that you're not logged into. so the app tries to upvote it from the perspective of that instance.

to better illustrate what's happening let's say that we have 2 instances: A and B. A federates B, i am only logged in to B, but when browsing all the posts in A i also see posts from B. now if i upvote them nothing will happen because i was browsing it from the context of A, (aka. i was interacting with A's server)

i hope i made it understandable. this is something that we are aware of and really want to improve in the future, tho we don't yet have a clear solution how to fix it.

**Comment by krawieck** [comment]
also, closing cuz duplicate
